### ISSUE TITLE
3D tutorial

### ISSUE THREAD

**Issue by lperozzi** [sdyinzhen/AutoBEL_Python#1]
Hi @sdyinzhen,

first of all many thanks to provide such a wonderful tool. I'm wondering if it is possible to run a 3D autoBEL, as you describe in your paper (i,.: using 75 layers in Z dimension instead of 1). I guess i need to made some modification to the code, isn't?

Many thanks for your work again

**Comment by sdyinzhen** [comment]
Hi Iperozzi,

The code can handle 3D. No need to modify it. Just change the "z_dim" input parameter to the layer number that your data have. But make sure that dimensions parameter are correct. A tutorial with 3D data will be provided latter. 

Cheers,
David

**Comment by lperozzi** [comment]
Many thanks @sdyinzhen. For the prior MC realizations, do you use an opensource python code? If yes, we could have access to it?

**Comment by sdyinzhen** [comment]
Hi @lperozzi , 

For the paper, we used a commercial modelling software named Petrel to generate prior realizations. Its modeling package is similar to GSLIB, while GSLIB python package can be font at: https://github.com/GeostatsGuy/GeostatsPy
